site_name: RK Website
site_url: https://www.ricardokleber.com.br
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/images/rk_logo.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    admonition:
      example: fontawesome/brands/youtube
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true # Adiciona links permanentes aos cabeçalhos
      title: Índice
nav:
  - Início: index.md
  - Canais Youtube:
    - Canal @rkifrn: https://www.youtube.com/@rkifrn
    - Canal @segurancaderedes: https://www.youtube.com/@segurancaderedes
    - Canal @ricardokleber: https://www.youtube.com/@ricardokleber
  - Cursos em Videoaulas:
    - Fundamentos de Computação Forense: https://www.udemy.com/course/fundamentos-de-computacao-forense/
    - Computação Forense em Mídias Não Voláteis: https://www.udemy.com/course/computacao-forense-em-midias/
  - Livros:
    - Introdução à Análise Forense em Redes (E-Book): https://www.amazon.com.br/Introdu%C3%A7%C3%A3o-An%C3%A1lise-Forense-Redes-Computadores-ebook/dp/B0CTXHPHN7
    - Introdução à Análise Forense em Redes (Livro Físico): https://www.amazon.com.br/Introdu%C3%A7%C3%A3o-An%C3%A1lise-Forense-Redes-Computadores/dp/B0CTVLTQS4/
  - Ambientes EaD:
    - Ava/Moodle IFRN/CN: https://ead.projetos.cn.ifrn.edu.br
    - Ava/Moodle EHA/IFRN: https://ead.eha.net.br
  - IFRN/CN:
    - 2025.2:
      - "Horários RK (2025.2)": ifrn/20252.md
      - "[INT.INF.2M] Redes de Computadores": ifrn/tin1160.md
      - "[TEC.INF.4M] Sistemas Distribuídos": ifrn/tec1031.md      
      - "[TEC.INF.4M] Aplicações de Redes de Computadores": ifrn/tec1032.md 
      - "[TEC.INF.6T] Segurança e Preservação de Dados": ifrn/tec0700.md 
    - 2025.1:
      - "Horários RK (2025.1)": ifrn/20251.md
      - "[TEC.INF.3M] Redes de Computadores": ifrn/tec0678.md
      - "[INT.INF.2M] Redes de Computadores": ifrn/tin1160.md      
      - "[INT.MS.3M] Infraestrutura de Redes de Computadores": ifrn/tin0454.md
      - "[INT.INF.4M] Fund.Sist.Operacionais e S.O.de Redes": ifrn/tin0022.md
  - Projetos:
    - Academia do Hacker Ético: https://www.eha.net.br
  - Sobre:
    - Quem sou eu?: sobre/quemsoueu.md
    - Currículo Lattes: http://lattes.cnpq.br/1198509733142922
  - Contatos:
    - E-mails: contatos/emails.md
    - Endereço (Correspondência): contatos/endereco.md 
  - Linkedin: https://br.linkedin.com/in/ricardokleber